<template>
  <div class="dictionary-page">
    <PageHeader title="通用字典" subtitle="维护租户字典类型与字典项，为业务表单提供统一枚举数据" />
    <el-tabs v-model="activeTab">
      <el-tab-pane label="字典类型" name="types">
        <section class="panel">
          <div class="panel-header toolbar"><div><h2>字典类型</h2><span class="hint">APP-01 · /tenant-access/dictionaries</span></div><el-button type="primary" @click="openTypeDialog()">新增字典类型</el-button></div>
          <div class="panel-body">
            <el-form :inline="true" :model="typeQuery" class="query-form" @submit.prevent="loadTypes"><el-form-item label="关键字"><el-input v-model="typeQuery.keyword" clearable placeholder="编码或名称" @keyup.enter="loadTypes" /></el-form-item><el-form-item label="状态"><el-select v-model="typeQuery.status" clearable placeholder="全部" style="width: 130px"><el-option label="启用" value="ACTIVE" /><el-option label="停用" value="INACTIVE" /></el-select></el-form-item><el-form-item><el-button type="primary" @click="loadTypes">查询</el-button><el-button @click="resetTypeQuery">重置</el-button></el-form-item></el-form>
            <el-table v-loading="typesLoading" :data="types" row-key="dictionaryTypeId"><el-table-column prop="dictionaryCode" label="字典编码" min-width="170"><template #default="{ row }"><span class="mono">{{ row.dictionaryCode }}</span></template></el-table-column><el-table-column prop="dictionaryName" label="字典名称" min-width="150" /><el-table-column prop="description" label="说明" min-width="180" show-overflow-tooltip /><el-table-column label="状态" width="90"><template #default="{ row }"><StatusTag :code="row.status" /></template></el-table-column><el-table-column prop="lockVersion" label="锁版本" width="90" /><el-table-column prop="updatedAt" label="更新时间" width="170" /><el-table-column label="操作" width="190" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="selectType(row)">管理字典项</el-button><el-button link @click="openTypeDialog(row)">编辑</el-button></template></el-table-column></el-table>
            <el-pagination v-model:current-page="typePage" v-model:page-size="typeSize" class="pagination" layout="total, sizes, prev, pager, next" :total="typeTotal" :page-sizes="[10, 20, 50]" @current-change="loadTypes" @size-change="loadTypes" />
          </div>
        </section>
      </el-tab-pane>
      <el-tab-pane label="字典项" name="items">
        <section class="panel"><div class="panel-header toolbar"><div><h2>字典项 <span v-if="selectedType" class="selected-code mono">{{ selectedType.dictionaryCode }}</span></h2><span class="hint">支持层级父项、排序和启停状态</span></div><el-button type="primary" :disabled="!selectedType" @click="openItemDialog()">新增字典项</el-button></div><div class="panel-body">
          <el-alert v-if="!selectedType" title="请先在“字典类型”中选择一个字典管理字典项" type="info" :closable="false" show-icon />
          <template v-else><el-form :inline="true" :model="itemQuery" class="query-form" @submit.prevent="loadItems"><el-form-item label="关键字"><el-input v-model="itemQuery.keyword" clearable placeholder="项编码或名称" @keyup.enter="loadItems" /></el-form-item><el-form-item label="状态"><el-select v-model="itemQuery.status" clearable placeholder="全部" style="width: 130px"><el-option label="启用" value="ACTIVE" /><el-option label="停用" value="INACTIVE" /></el-select></el-form-item><el-form-item><el-button type="primary" @click="loadItems">查询</el-button><el-button @click="resetItemQuery">重置</el-button></el-form-item></el-form>
          <el-table v-loading="itemsLoading" :data="items" row-key="dictionaryItemId"><el-table-column prop="itemCode" label="项编码" min-width="170"><template #default="{ row }"><span class="mono">{{ row.itemCode }}</span></template></el-table-column><el-table-column prop="itemName" label="项名称" min-width="150" /><el-table-column prop="parentItemId" label="父项 ID" min-width="170"><template #default="{ row }"><span class="mono">{{ row.parentItemId || '-' }}</span></template></el-table-column><el-table-column prop="sortOrder" label="排序" width="80" /><el-table-column label="状态" width="90"><template #default="{ row }"><StatusTag :code="row.status" /></template></el-table-column><el-table-column prop="lockVersion" label="锁版本" width="90" /><el-table-column label="操作" width="90" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="openItemDialog(row)">编辑</el-button></template></el-table-column></el-table>
          <el-pagination v-model:current-page="itemPage" v-model:page-size="itemSize" class="pagination" layout="total, sizes, prev, pager, next" :total="itemTotal" :page-sizes="[10, 20, 50]" @current-change="loadItems" @size-change="loadItems" /></template>
        </div></section>
      </el-tab-pane>
    </el-tabs>
    <el-dialog v-model="typeDialogVisible" :title="editingType ? '编辑字典类型' : '新增字典类型'" width="520px"><el-form ref="typeFormRef" :model="typeForm" :rules="typeRules" label-position="top"><el-form-item label="字典编码" prop="dictionaryCode"><el-input v-model="typeForm.dictionaryCode" :disabled="Boolean(editingType)" maxlength="64" placeholder="例如：HERB_PART_TYPE" @input="normalizeCode" /></el-form-item><el-form-item label="字典名称" prop="dictionaryName"><el-input v-model="typeForm.dictionaryName" maxlength="128" /></el-form-item><el-form-item label="字典说明"><el-input v-model="typeForm.description" type="textarea" :rows="3" maxlength="500" /></el-form-item><el-form-item v-if="editingType" label="状态"><el-switch v-model="typeForm.active" active-text="启用" inactive-text="停用" /></el-form-item></el-form><template #footer><el-button @click="typeDialogVisible = false">取消</el-button><el-button type="primary" :loading="dialogSubmitting" @click="submitType">保存</el-button></template></el-dialog>
    <el-dialog v-model="itemDialogVisible" :title="editingItem ? '编辑字典项' : '新增字典项'" width="520px"><el-form ref="itemFormRef" :model="itemForm" :rules="itemRules" label-position="top"><el-form-item label="字典项编码" prop="itemCode"><el-input v-model="itemForm.itemCode" :disabled="Boolean(editingItem)" maxlength="64" /></el-form-item><el-form-item label="字典项名称" prop="itemName"><el-input v-model="itemForm.itemName" maxlength="128" /></el-form-item><div class="form-grid"><el-form-item label="父字典项 ID"><el-select v-model="itemForm.parentItemId" clearable filterable placeholder="可选，选择有效父项" style="width: 100%"><el-option v-for="parent in activeItems" :key="parent.dictionaryItemId" :label="parent.itemCode + ' · ' + parent.itemName" :value="parent.dictionaryItemId" /></el-select></el-form-item><el-form-item label="排序号"><el-input-number v-model="itemForm.sortOrder" :min="0" :max="2147483647" controls-position="right" style="width: 100%" /></el-form-item></div><el-form-item v-if="editingItem" label="状态"><el-switch v-model="itemForm.active" active-text="启用" inactive-text="停用" /></el-form-item></el-form><template #footer><el-button @click="itemDialogVisible = false">取消</el-button><el-button type="primary" :loading="dialogSubmitting" @click="submitItem">保存</el-button></template></el-dialog>
  </div>
</template>

<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { ElMessage, type FormInstance, type FormRules } from 'element-plus';
import PageHeader from '@/components/common/PageHeader.vue';
import StatusTag from '@/components/common/StatusTag.vue';
import { apiErrorMessage } from '@/api/client';
import { dictionaryApi, type DictionaryItem, type DictionaryType } from '@/api/dictionary';
const activeTab = ref('types'); const types = ref<DictionaryType[]>([]); const items = ref<DictionaryItem[]>([]); const activeItems = ref<DictionaryItem[]>([]); const selectedType = ref<DictionaryType | null>(null); const typesLoading = ref(false); const itemsLoading = ref(false); const dialogSubmitting = ref(false);
const typePage = ref(1); const typeSize = ref(10); const typeTotal = ref(0); const itemPage = ref(1); const itemSize = ref(10); const itemTotal = ref(0); const typeQuery = reactive({ keyword: '', status: '' }); const itemQuery = reactive({ keyword: '', status: '' });
const typeDialogVisible = ref(false); const itemDialogVisible = ref(false); const editingType = ref<DictionaryType | null>(null); const editingItem = ref<DictionaryItem | null>(null); const typeFormRef = ref<FormInstance>(); const itemFormRef = ref<FormInstance>(); const typeForm = reactive({ dictionaryCode: '', dictionaryName: '', description: '', active: true }); const itemForm = reactive({ itemCode: '', itemName: '', parentItemId: '', sortOrder: 0, active: true });
const typeRules: FormRules = { dictionaryCode: [{ required: true, message: '请输入字典编码', trigger: 'blur' }, { pattern: /^[A-Z][A-Z0-9_]{1,63}$/, message: '需以大写字母开头，仅支持大写字母、数字和下划线', trigger: 'blur' }], dictionaryName: [{ required: true, message: '请输入字典名称', trigger: 'blur' }] }; const itemRules: FormRules = { itemCode: [{ required: true, message: '请输入字典项编码', trigger: 'blur' }], itemName: [{ required: true, message: '请输入字典项名称', trigger: 'blur' }] };
const normalizeCode = (value: string) => { typeForm.dictionaryCode = value.trimStart().toUpperCase().replace(/[^A-Z0-9_]/g, '_'); };
const loadTypes = async () => { typesLoading.value = true; try { const result = await dictionaryApi.listTypes({ ...typeQuery, page: String(typePage.value), size: String(typeSize.value) }); types.value = result.records || []; typeTotal.value = Number(result.total || 0); } catch (error) { ElMessage.error(apiErrorMessage(error, '字典类型加载失败')); } finally { typesLoading.value = false; } };
const loadItems = async () => { if (!selectedType.value) return; itemsLoading.value = true; try { const [result, enabled] = await Promise.all([dictionaryApi.listItems(selectedType.value.dictionaryCode, { ...itemQuery, page: String(itemPage.value), size: String(itemSize.value) }), dictionaryApi.listActiveItems(selectedType.value.dictionaryCode)]); items.value = result.records || []; activeItems.value = enabled || []; itemTotal.value = Number(result.total || 0); } catch (error) { ElMessage.error(apiErrorMessage(error, '字典项加载失败')); } finally { itemsLoading.value = false; } };
const resetTypeQuery = () => { Object.assign(typeQuery, { keyword: '', status: '' }); typePage.value = 1; loadTypes(); }; const resetItemQuery = () => { Object.assign(itemQuery, { keyword: '', status: '' }); itemPage.value = 1; loadItems(); }; const selectType = (type: DictionaryType) => { selectedType.value = type; activeTab.value = 'items'; itemPage.value = 1; resetItemQuery(); };
const openTypeDialog = (type?: DictionaryType) => { editingType.value = type || null; Object.assign(typeForm, { dictionaryCode: type?.dictionaryCode || '', dictionaryName: type?.dictionaryName || '', description: type?.description || '', active: type?.status !== 'INACTIVE' }); typeDialogVisible.value = true; }; const openItemDialog = (item?: DictionaryItem) => { if (!selectedType.value) return; editingItem.value = item || null; Object.assign(itemForm, { itemCode: item?.itemCode || '', itemName: item?.itemName || '', parentItemId: item?.parentItemId || '', sortOrder: item?.sortOrder || 0, active: item?.status !== 'INACTIVE' }); itemDialogVisible.value = true; };
const submitType = async () => { if (!await typeFormRef.value?.validate().catch(() => false)) return; dialogSubmitting.value = true; try { if (editingType.value) await dictionaryApi.updateType(editingType.value.dictionaryTypeId, { dictionaryName: typeForm.dictionaryName.trim(), description: typeForm.description.trim() || undefined, status: typeForm.active ? 'ACTIVE' : 'INACTIVE', lockVersion: editingType.value.lockVersion }); else await dictionaryApi.createType({ dictionaryCode: typeForm.dictionaryCode.trim(), dictionaryName: typeForm.dictionaryName.trim(), description: typeForm.description.trim() || undefined }); ElMessage.success(editingType.value ? '字典类型更新成功' : '字典类型创建成功'); typeDialogVisible.value = false; await loadTypes(); } catch (error) { ElMessage.error(apiErrorMessage(error, '字典类型保存失败')); } finally { dialogSubmitting.value = false; } };
const submitItem = async () => { if (!selectedType.value || !await itemFormRef.value?.validate().catch(() => false)) return; dialogSubmitting.value = true; try { const parentItemId = itemForm.parentItemId.trim() || undefined; if (editingItem.value) await dictionaryApi.updateItem(selectedType.value.dictionaryCode, editingItem.value.dictionaryItemId, { itemName: itemForm.itemName.trim(), parentItemId, sortOrder: itemForm.sortOrder, status: itemForm.active ? 'ACTIVE' : 'INACTIVE', lockVersion: editingItem.value.lockVersion }); else await dictionaryApi.createItem(selectedType.value.dictionaryCode, { itemCode: itemForm.itemCode.trim(), itemName: itemForm.itemName.trim(), parentItemId, sortOrder: itemForm.sortOrder }); ElMessage.success(editingItem.value ? '字典项更新成功' : '字典项创建成功'); itemDialogVisible.value = false; await loadItems(); } catch (error) { ElMessage.error(apiErrorMessage(error, '字典项保存失败')); } finally { dialogSubmitting.value = false; } };
onMounted(loadTypes);
</script>
<style scoped>
.toolbar { display: flex; justify-content: space-between; align-items: center; gap: 16px; } .toolbar h2 { display: inline; } .hint { display: block; margin-top: 6px; color: var(--color-muted); font-size: 12px; } .selected-code { margin-left: 8px; color: var(--color-brand); font-size: 13px; font-weight: 500; } .query-form { margin-bottom: 16px; } .pagination { justify-content: flex-end; margin-top: 18px; } .form-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; } @media (max-width: 760px) { .toolbar { align-items: flex-start; flex-direction: column; } .form-grid { grid-template-columns: 1fr; gap: 0; } }
</style>
